title: PyBaMM Battery Modelling Conference
description: Conference site for PyBaMM battery modelling community.
logo_text: PyBaMM Conference
logo_url: /assets/img/pybamm-logo.png
# register_url: https://estore.imperial.ac.uk/conferences-and-events/faculty-of-engineering/mechanical-engineering/pybamm-conference/pybamm-conference-2025
programme_url: https://cdn.prod.website-files.com/667303565fdbef00f25296e9/67a0ca8c05d7e2bce9f2f378_PyBaMM%20Conference%20agenda%202025.pdf
abstracts_pdf_url: https://cdn.prod.website-files.com/667303565fdbef00f25296e9/67a0ca92d359b147cbf5f02e_Book%20of%20abstracts.pdf
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  # - title: Speakers
  #   url: /speakers/
  # - title: Abstracts
  #   url: /abstracts/
  - title: Venue
    url: /venue/
  - title: Application
    url: /submission/
  - title: Registration
    url: /registration/
  # - title: Training
  #   url: /training/
hero_images:
  - https://cdn.prod.website-files.com/667303565fdbef00f25296e9/6674b57368d114840a35f3a3_PyBamm3.avif
  - https://cdn.prod.website-files.com/667303565fdbef00f25296e9/6674b574cfebb0222cf13d9e_PyBamm1.avif
  - https://cdn.prod.website-files.com/667303565fdbef00f25296e9/6674b574fe30fcedf3e1166c_PyBamm4.avif
  - https://cdn.prod.website-files.com/667303565fdbef00f25296e9/6674b575765d16d53bc86c4c_PyBamm22.avif
  - https://cdn.prod.website-files.com/667303565fdbef00f25296e9/6674b574f644214dcfb33d05_PyBamm18.avif
  - https://cdn.prod.website-files.com/667303565fdbef00f25296e9/6674b5750d0a64b4a45aa839_PyBamm16.avif
